[phases.setup]
nixPkgs = [
  "go",
  "postgresql"
]

commands = [
  "go mod tidy",
  "go build -o ecowitt_app"
]

[phases.start]
commands = [
  "./ecowitt_app"
]

[env]
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
POSTGRES_DB = "postgre"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "0OelK6MKgpH0l9HnO91uOv2s5JtE3RPRlKqKOqp1dLJM0jFsxQxBrmiJGiBDxrFYp"

[ports]
app = 8080
